### ISSUE TITLE
Uncaught Error: Can't undo with an open transaction

### ISSUE THREAD

**Issue by ricardopinto** [atom/autocomplete#57]
Uncaught Error: Can't undo with an open transaction

**Atom Version**: 0.158.0
**System**: Mac OS X 10.10.1
**Thrown From**: [autocomplete](https://github.com/atom/autocomplete) package, v0.34.0

### Steps To Reproduce

1. Just pressed Ctrl + Space to autocomplete a variable name (in Elixir), it displayed this error and didn't autocomplete. It's not happening consistently.

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:73

Error: Can't undo with an open transaction
  at History.module.exports.History.undo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:73:15)
  at History.module.exports.History.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:185:16)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:710:27)
  at TextEditor.module.exports.TextEditor.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1166:26)
  at AutocompleteView.module.exports.AutocompleteView.cancelled (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete-view.js:172:21)
  at AutocompleteView.module.exports.SelectListView.cancel (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:260:14)
  at atom-text-editor.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:76:26)
  at atom-text-editor.jQuery.event.dispatch (/Users/ricardopinto/.atom/packages/build/node_modules/space-pen/vendor/jquery.js:4676:9)
  at atom-text-editor.elemData.handle (/Users/ricardopinto/.atom/packages/build/node_modules/space-pen/vendor/jquery.js:4360:46)
  at atom-text-editor.jQuery.event.special.focus.trigger (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4842:11)
  at Object.jQuery.event.trigger (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4565:60)
  at atom-text-editor.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5124:17)
  at Function.jQuery.extend.each (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:590:23)
  at TextEditorView.jQuery.fn.jQuery.each (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:237:17)
  at TextEditorView.jQuery.fn.extend.trigger (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5123:15)
  at TextEditorView.jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:56:28)
  at TextEditorView.jQuery.fn.(anonymous function) [as focus] (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:6733:9)
  at AutocompleteView.module.exports.AutocompleteView.cancel (/Users/ricardopinto/.atom/packages/autocomplete-plus-async/lib/autocomplete-view.coffee:143:19)
  at AutocompleteView.cancel (/Users/ricardopinto/.atom/packages/autocomplete-plus-async/lib/autocomplete-view.coffee:1:1)
  at AutocompleteView.module.exports.AutocompleteView.onChanged (/Users/ricardopinto/.atom/packages/autocomplete-plus-async/lib/autocomplete-view.coffee:226:8)
  at /Users/ricardopinto/.atom/packages/autocomplete-plus-async/lib/autocomplete-view.coffee:1:1
  at TextBuffer.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:591:12)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:503:12)
  at TextBuffer.module.exports.TextBuffer.delete (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:600:19)
  at Selection.module.exports.Selection.deleteSelectedText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:556:37)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete-view.js:258:23
  at Array.forEach (native)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete-view.js:254:22
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:112:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:683:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1146:26)
  at AutocompleteView.module.exports.AutocompleteView.replaceSelectedTextWithMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete-view.js:250:26)
  at AutocompleteView.module.exports.AutocompleteView.selectItemView (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete-view.js:93:21)
  at AutocompleteView.module.exports.SelectListView.populateList (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:207:21)
  at AutocompleteView.module.exports.AutocompleteView.populateList (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete-view.js:329:54)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/lib/select-list-view.js:347:26

```

/cc @atom/core

**Comment by maxbrunsfeld** [comment]
This was fixed a while back. Please upgrade to the latest Atom.

**Comment by remzisenel** [comment]
Steps to reproduce: 

1. Ctrl-Space to toggle autocompletion.
2. Use down arrow to navigate through the list.

**Atom Version**: 0.175.0
**System**: Mac OS X 10.10.2
**Thrown From**: [autocomplete](https://github.com/atom/autocomplete) package, v0.43.0

### Stack Trace

Uncaught Error: Can't undo with an open transaction

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:76

Error: Can't undo with an open transaction
  at History.module.exports.History.undo (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:76:15)
  at History.module.exports.History.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:188:16)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:714:27)
  at TextEditor.module.exports.TextEditor.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1198:26)
  at AutocompleteView.module.exports.AutocompleteView.cancelled (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete-view.js:174:21)
  at AutocompleteView.module.exports.SelectListView.cancel (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/lib/select-list-view.js:260:14)
  at atom-text-editor.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/lib/select-list-view.js:76:26)
  at atom-text-editor.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at atom-text-editor.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)
  at atom-text-editor.jQuery.event.special.focus.trigger (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4842:11)
  at Object.jQuery.event.trigger (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4565:60)
  at atom-text-editor.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5124:17)
  at Function.jQuery.extend.each (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:590:23)
  at TextEditorView.jQuery.fn.jQuery.each (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:237:17)
  at TextEditorView.jQuery.fn.extend.trigger (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:5123:15)
  at TextEditorView.jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:56:28)
  at TextEditorView.jQuery.fn.(anonymous function) [as focus] (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:6733:9)
  at AutocompleteView.module.exports.AutocompleteView.cancel (/Users/remzi/.atom/packages/autocomplete-plus-async/lib/autocomplete-view.coffee:143:19)
  at AutocompleteView.cancel (/Users/remzi/.atom/packages/autocomplete-plus-async/lib/autocomplete-view.coffee:1:1)
  at AutocompleteView.module.exports.AutocompleteView.onChanged (/Users/remzi/.atom/packages/autocomplete-plus-async/lib/autocomplete-view.coffee:226:8)
  at /Users/remzi/.atom/packages/autocomplete-plus-async/lib/autocomplete-view.coffee:1:1
  at TextBuffer.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.applyPatch (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:595:12)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:507:12)
  at TextBuffer.module.exports.TextBuffer.delete (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:604:19)
  at Selection.module.exports.Selection.deleteSelectedText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:556:37)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete-view.js:265:23
  at Array.forEach (native)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete-view.js:261:22
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1178:26)
  at AutocompleteView.module.exports.AutocompleteView.replaceSelectedTextWithMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete-view.js:257:26)
  at AutocompleteView.module.exports.AutocompleteView.selectItemView (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete-view.js:93:21)
  at AutocompleteView.module.exports.SelectListView.selectNextItemView (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/lib/select-list-view.js:298:19)
  at AutocompleteView.module.exports.AutocompleteView.selectNextItemView (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete-view.js:98:53)
  at space-pen-div.atom.commands.add.core:move-down (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/lib/select-list-view.js:89:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
  3x -2:13.5 autocomplete:toggle (atom-text-editor.editor.is-focused)
     -1:50.1 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:49.7 core:backspace (atom-text-editor.editor.is-focused)
     -1:49.4 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -1:49.2 core:backspace (atom-text-editor.editor.is-focused)
  3x -1:48.6 core:save (atom-text-editor.editor.is-focused)
     -0:09.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:07.7 autocomplete:toggle (atom-text-editor.editor.is-focused)
     -0:06.8 core:confirm (atom-text-editor.editor.mini)
     -0:04.9 autocomplete:toggle (atom-text-editor.editor.is-focused)
     -0:04.0 core:backspace (atom-text-editor.editor.mini)
  2x -0:03.3 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:03.3 core:cancel (atom-text-editor.editor.mini)
     -0:02.3 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.0 autocomplete:toggle (atom-text-editor.editor.is-focused)
     -0:00.0 core:move-down (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".meta"
    ],
    "disabledPackages": [
      "autocomplete-plus-async"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-csharp, v0.3.0
omnisharp-atom, v0.1.6

# Dev
No dev packages
```

/cc @atom/core

**Comment by maxbrunsfeld** [comment]
I see that you have the `autocomplete-plus-async` package disabled, but its code is still present in your stack trace. Can you try `rm -rf .atom/packages/autocomplete-plus-async` and see if this still happens?

**Comment by remzisenel** [comment]
Thank you Max, that worked. Sorry for the faulty bug report.

**Comment by maxbrunsfeld** [comment]
Great; no problem!

**Comment by luisrudge** [comment]
I'm still having this problem.

**Comment by guillaume86** [comment]
I have this issue, but no autocomplete-async in my stacktrace:

```
C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\text-buffer\lib\history.js:80
Hide Stack Trace
Error: Can't undo with an open transaction
  at History.module.exports.History.undo (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\text-buffer\lib\history.js:80:15)
  at History.module.exports.History.revertToCheckpoint (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\text-buffer\lib\history.js:192:16)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:714:27)
  at TextEditor.module.exports.TextEditor.revertToCheckpoint (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\src\text-editor.js:1231:26)
  at AutocompleteView.module.exports.AutocompleteView.cancelled (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\autocomplete\lib\autocomplete-view.js:174:21)
  at AutocompleteView.module.exports.SelectListView.cancel (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:263:14)
  at atom-text-editor.<anonymous> (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:76:26)
  at atom-text-editor.jQuery.event.dispatch (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\jquery\dist\jquery.js:4430:9)
  at atom-text-editor.elemData.handle (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\jquery\dist\jquery.js:4116:28)
  at ViewManager.module.exports.ViewManager.focusEditor (C:\Users\guill_000\.atom\packages\atom-ternjs\lib\atom-ternjs-view-manager.coffee:35:15)
  at ViewManager.module.exports.ViewManager.hideRename (C:\Users\guill_000\.atom\packages\atom-ternjs\lib\atom-ternjs-view-manager.coffee:29:10)
  at C:\Users\guill_000\.atom\packages\atom-ternjs\lib\atom-ternjs-manager.coffee:88:23
  at Emitter.module.exports.Emitter.emit (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.cursorMoved (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\src\text-editor.js:1712:27)
  at C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\src\cursor.js:62:31
  at Emitter.module.exports.Emitter.emit (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Marker.module.exports.Marker.resumeChangeEvents (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\src\marker.js:321:24)
  at DisplayBuffer.module.exports.DisplayBuffer.resumeMarkerChangeEvents (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\src\display-buffer.js:1383:16)
  at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\src\display-buffer.js:332:19)
  at DisplayBuffer.module.exports.DisplayBuffer.handleBufferMarkersUpdated (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\src\display-buffer.js:1582:21)
  at C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\src\display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:599:20)
  at TextBuffer.module.exports.TextBuffer.setTextInRange (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:511:12)
  at TextBuffer.module.exports.TextBuffer.delete (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:604:19)
  at Selection.module.exports.Selection.deleteSelectedText (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\src\selection.js:564:37)
  at C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\autocomplete\lib\autocomplete-view.js:265:23
  at Array.forEach (native)
  at C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\autocomplete\lib\autocomplete-view.js:261:22
  at History.module.exports.History.transact (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\text-buffer\lib\history.js:119:18)
  at TextBuffer.module.exports.TextBuffer.transact (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\src\text-editor.js:1211:26)
  at AutocompleteView.module.exports.AutocompleteView.replaceSelectedTextWithMatch (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\autocomplete\lib\autocomplete-view.js:257:26)
  at AutocompleteView.module.exports.AutocompleteView.selectItemView (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\autocomplete\lib\autocomplete-view.js:93:21)
  at AutocompleteView.module.exports.SelectListView.selectNextItemView (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:301:19)
  at AutocompleteView.module.exports.AutocompleteView.selectNextItemView (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\autocomplete\lib\autocomplete-view.js:98:53)
  at space-pen-div.atom.commands.add.core:move-down (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\atom-space-pen-views\lib\select-list-view.js:89:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\src\command-registry.js:242:29)
  at C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\guill_000\AppData\Local\atom\app-0.188.0\resources\app\src\window-event-handler.js:180:20)
```

**Comment by maxbrunsfeld** [comment]
@guillaume86 does this happen in `--safe` mode? What packages do you have installed (`apm list`)?

**Comment by guillaume86** [comment]
It's not happening in safe mode, it's related to http://github.com/tststs/atom-ternjs.
I was actually testing it for the first time when it happened and I have no problems in projects where ternjs is not enabled.

**Comment by admmasters** [comment]
Just had this issue - used Ctrl + Space to autocomplete and received the above. OS X 10.10.3.

**Comment by lee-dohm** [comment]
@admmasters Can you reproduce after completely exiting all instance of Atom and starting it again with `atom --safe`?
