### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by CosminTraistaru** [atom/autocomplete#64]
[Enter steps to reproduce below:]

1. Cmd+Shift+P
2. enter 'autocomplete'
3. select "autocomplete next"
python code

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.1
**Thrown From**: [autocomplete](https://github.com/atom/autocomplete) package, v0.43.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete.js:42

TypeError: undefined is not a function
  at /Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete.js:42:68
  at atom-text-editor.deactivationDisposables.add.atom.commands.add.autocomplete:next (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete.js:53:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/lib/select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -2:56.2 editor:consolidate-selections (atom-text-editor.editor.mini)
     -2:56.2 core:cancel (atom-text-editor.editor.mini)
     -2:38.7 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:36.4 core:confirm (atom-text-editor.editor.mini)
     -2:36.4 window:install-shell-commands (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:50.4 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:46.6 core:confirm (atom-text-editor.editor.mini)
     -0:46.6 autocomplete:toggle (atom-text-editor.editor.is-focused)
  2x -0:44.9 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:44.9 core:cancel (atom-text-editor.editor.mini)
 19x -0:39.7 core:backspace (atom-text-editor.editor.is-focused)
     -0:08.7 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:08.7 core:cancel (atom-text-editor.editor.is-focused)
     -0:07.3 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.6 core:confirm (atom-text-editor.editor.mini)
     -0:00.6 autocomplete:next (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
linter-python-pep8, v0.2.0
linter-python-pyflakes, v0.1.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
Could you try safe mode (`atom --safe`) and see if this still happens?

**Comment by CosminTraistaru** [comment]
Sorry for the late response, yes, reproducible in safe mode also.
