### ISSUE TITLE
Uncaught Error: Cannot create a checkpoint inside of a transaction

### ISSUE THREAD

**Issue by graemerocher** [atom/autocomplete#65]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.1
**Thrown From**: [autocomplete](https://github.com/atom/autocomplete) package, v0.43.0

### Stack Trace

Uncaught Error: Cannot create a checkpoint inside of a transaction

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:174

Error: Cannot create a checkpoint inside of a transaction
  at History.module.exports.History.createCheckpoint (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:174:15)
  at TextBuffer.module.exports.TextBuffer.createCheckpoint (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:710:27)
  at TextEditor.module.exports.TextEditor.createCheckpoint (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1197:26)
  at AutocompleteView.module.exports.AutocompleteView.attach (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete-view.js:182:37)
  at AutocompleteView.module.exports.AutocompleteView.toggle (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete-view.js:215:21)
  at atom-text-editor.deactivationDisposables.add.atom.commands.add.autocomplete:toggle (/Applications/Atom.app/Contents/Resources/app/node_modules/autocomplete/lib/autocomplete.js:48:70)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -0:22.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode)
     -0:20.4 core:move-down (input.hidden-input)
     -0:19.8 core:move-up (atom-text-editor.editor.vim-mode.insert-mode)
     -0:19.3 editor:select-to-first-character-of-line (atom-text-editor.editor.vim-mode.insert-mode)
     -0:18.9 core:delete (atom-text-editor.editor.vim-mode.insert-mode)
     -0:17.4 core:close (atom-text-editor.editor.vim-mode.insert-mode)
     -0:16.6 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:15.7 core:confirm (atom-text-editor.editor.mini)
     -0:12.3 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
 12x -0:11.1 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:09.3 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:08.6 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  5x -0:06.6 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:03.3 core:move-down (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:01.8 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:00.7 autocomplete:toggle (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-grails, v0.1.0
autocomplete-plus, v2.0.1
file-icons, v1.4.8
language-groovy, v0.3.0
travis-ci-status, v0.11.2
vim-mode, v0.30.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by kevinsawicki** [comment]
This package is deprecated and no longer shipped with Atom. If this is still an issue using the [autocomplete-plus](https://github.com/atom/autocomplete-plus) package, please open up a new issue on that repository, thanks.
